name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   build:

      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v2
      - name: Switch to Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Show Available Destinations
        run: |
         xcodebuild -scheme 'Hacktoberfest iOS' -showdestinations
      - name: Build
        env:
          Project: "Hacktoberfest iOS.xcodeproj"
          SCHEME: "Hacktoberfest iOS"
          DESTINATION: platform=iOS Simulator,OS=14.0,name=iPhone 11
        run: |
         xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release build CODE_SIGNING_ALLOWED=NO
